### ISSUE TITLE
Libre engine is asking for an API key 

### ISSUE THREAD

**Issue by opheliagame** [franciscop/translate#26]
When trying to get translations using libre engine the promise gets rejected with the following message 
`Error: Please contact the server operator to obtain an API key` 

I am wondering if the libre api changed or something else because the process exits with a non zero code. 
I was able to do this only a few months back.

**Comment by demoprazol** [comment]
Same +1

**Comment by opheliagame** [comment]
I think [this issue](https://github.com/uav4geo/LibreTranslate/issues/82) is the reason

**Comment by franciscop** [comment]
This is fairly expected since I'm sure a free service like this would get abused at some point. To fix it, you can either get a key from the official website or install Libretranslate on your own server and specify the URL+Key:

```js
// Use the key with the official website
translate.key = process.env.LIBRE_KEY;

// OR

// Install in your own server and set up the URL and key:
translate.url = "https://example.com/";
translate.key = process.env.LIBRE_KEY;
```

This should be added as a note somewhere in translate documentation though, so I'll leave the issue it open for now.

**Comment by franciscop** [comment]
Added two notes on the README regarding Libretranslate, so I'm closing this issue :)
