### ISSUE TITLE
Google does not work anymore

### ISSUE THREAD

**Issue by scheepers** [franciscop/translate#27]
At first the translate() returns an error and says a key is required.
And now (After getting a key and putting it in translate.key):

Error: API key not valid. Please pass a valid API key.

**Comment by franciscop** [comment]
It seems your API key is not valid? Did you get an API key like explained here?
https://translatepress.com/docs/automatic-translation/generate-google-api-key/

To debug it yourself, if you do `console.log(translate.key);` does it print your key properly?

Otherwise, could you please share some of your code (without the key itself) so we can help?

**Comment by franciscop** [comment]
Please confirm whether it works now, I believe it should be fixed on `translate@1.4.0`

**Comment by kadu** [comment]
Hi @franciscop , Here is working fine

**Comment by franciscop** [comment]
Awesome, thanks!
