### ISSUE TITLE
Missing important stuff

### ISSUE THREAD

**Issue by telkenes** [franciscop/translate#3]
you only give us the text at the end but not the starting language nor ending language.

console.log(text) only gives the text result and i want something like **text.from.lang** and **text.to.lang** even we can set it up Google and yandex can detect what language it is so it will be very usefull

**Comment by franciscop** [comment]
The ending language is not needed at all because it's always mandatory:

```js
const to = 'es';
const text = await translate('Hello world', to);
console.log(text, translate.from, to);
```

Since the starting language is `en`, you can access it from `translate.from` easily. As explained here, detecting languages is not within the scope of `translate` so even if we add that you do not need to specify the `from` language, getting the `from` original language will not be possible. Feel free to use this or similar packages for that: https://www.npmjs.com/package/languagedetect
