### ISSUE TITLE
Cannot import your module into my TS project

### ISSUE THREAD

**Issue by bytadaniel** [franciscop/translate#47]
<img width="1103" alt="Снимок экрана 2023-04-21 в 03 38 43" src="https://user-images.githubusercontent.com/59475531/233514342-e0b5e812-9d7f-404e-9ad2-7427fd23d7bf.png">

**Comment by franciscop** [comment]
It seems you are transpiling to `"module": "commonjs"`. The latest 2.x version of `translate` uses ESM (`import`/`export`), which should be used with `import` instead of `require()`. Even if you ARE using `import` in your code, since you have the module set to commonjs it's being transformed to require() internally. You can either:

- Use translate@1.x which is transpiled to UMD, which is compatible with `require()` -> `npm i translate@1`
- Change your code to ESM: see [this StackOverflow answer](https://stackoverflow.com/a/71215905/938236) or [this one if you use `ts-node-dev`](https://stackoverflow.com/a/74921691/938236).

**Comment by Inventsable** [comment]
It'd be nice to include this in the README

**Comment by franciscop** [comment]
@Inventsable [in recent Node versions](https://joyeecheung.github.io/blog/2024/03/18/require-esm-in-node-js/) you can require() an ESM module, so it really depends on what Node version and how you are importing things, which is up to the developer. Did you find this issue as well? I think this could be in e.g. a FAQ
