### ISSUE TITLE
[Feature Request] Return metadata with characters and words translated

### ISSUE THREAD

**Issue by capybarahero** [franciscop/translate#60]
Hi there! 

It'd be great to have the option to receive the effective number of characters and words translated by the engine as metadata (i.e. ignoring what came from cached). 

Why is it important? Since engines have different pricing models (and some offer a limited free tier),  we can store the total number of characters or words translated and define which engine to choose based on their current usage.

Hope it's clear!
Thanks again for creating and maintaining this package!

**Comment by franciscop** [comment]
This feels really niche AND hard (see below), so not something that should normally be in the core library. The easiest thing would be for you to assume nothing is cached, since for many applications that would be true and that would be on the safe side, and add a thin layer/wrapper on top of `translate()` to count those up.

> "we can store the total number of characters or words"

I've done some brief work on the past on sentence segmentation and let me tell you this library is _not_ going to be solving that problem, since that'd require a research team and few years.
